export const typography = {
	display: {
		"2xl": {
			regular: "4.5rem",
			medium: "4.5rem",
			semibold: "4.5rem",
			bold: "4.5rem",
		},
		xl: {
			regular: "3.75rem",
			medium: "3.75rem",
			semibold: "3.75rem",
			bold: "3.75rem",
		},
		lg: {
			regular: "3rem",
			medium: "3rem",
			semibold: "3rem",
			bold: "3rem",
		},
		md: {
			regular: "2.25rem",
			medium: "2.25rem",
			semibold: "2.25rem",
			bold: "2.25rem",
		},
		sm: {
			regular: "1.88rem",
			medium: "1.88rem",
			semibold: "1.88rem",
			bold: "1.88rem",
			"medium-italic": "1.88rem",
		},
		xs: {
			regular: "1.5rem",
			medium: "1.5rem",
			semibold: "1.5rem",
			bold: "1.5rem",
			"medium-italic": "1.5rem",
		},
	},
	text: {
		xl: {
			regular: "1.25rem",
			medium: "1.25rem",
			semibold: "1.25rem",
			bold: "1.25rem",
			"regular-italic": "1.25rem",
			"medium-italic": "1.25rem",
			"semibold-italic": "1.25rem",
			"bold-italic": "1.25rem",
			"regular-underlined": "1.25rem",
		},
		lg: {
			regular: "1.12rem",
			medium: "1.12rem",
			semibold: "1.12rem",
			bold: "1.12rem",
			"regular-italic": "1.12rem",
			"medium-italic": "1.12rem",
			"semibold-italic": "1.12rem",
			"bold-italic": "1.12rem",
			"regular-underlined": "1.12rem",
			"medium-underlined": "1.12rem",
			"semibold-underlined": "1.12rem",
		},
		md: {
			regular: "1rem",
			medium: "1rem",
			semibold: "1rem",
			bold: "1rem",
			"regular-italic": "1rem",
			"medium-italic": "1rem",
			"semibold-italic": "1rem",
			"bold-italic": "1rem",
			"regular-underlined": "1rem",
			"medium-underlined": "1rem",
			"semibold-underlined": "1rem",
		},
		sm: {
			regular: "0.88rem",
			medium: "0.88rem",
			semibold: "0.88rem",
			bold: "0.88rem",
			"regular-underlined": "0.88rem",
			"medium-underlined": "0.88rem",
			"semibold-underlined": "0.88rem",
		},
		xs: {
			regular: "0.75rem",
			medium: "0.75rem",
			semibold: "0.75rem",
			bold: "0.75rem",
		},
	},
	base: {},
};
